language: php

php:
  - 7.1
  - 7.2

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer update --prefer-dist --no-interaction

script:
    - ./vendor/bin/phpunit --coverage-clover clover.xml

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
