language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: 7.4snapshot

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer update --prefer-dist --no-interaction

script:
    - ./vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
